name: visualization_catalog
channels:
  - bokeh
  - conda-forge
  - defaults
dependencies:
  - bokeh=1.1.0
  - folium=0.8.3
  - jupyter=1.0.0
  - matplotlib==3.0.3
  - mpld3=0.3
  - pandas=0.24.2
  - pip=19.0.3
  - seaborn=0.9.0
  - pip:
    - jupyterthemes==0.20.0
